apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zeus-web-api-hpa
  namespace: zeus-eaa
  labels:
    app.kubernetes.io/name: zeus-eaa-compliance
    app.kubernetes.io/component: web-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zeus-web-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zeus-web-api-pdb
  namespace: zeus-eaa
  labels:
    app.kubernetes.io/name: zeus-eaa-compliance
    app.kubernetes.io/component: web-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeus-eaa-compliance
      app.kubernetes.io/component: web-api
